Cora:
  seed: 1234
  learning_rate: 0.0005
  num_hidden: 128
  num_proj_hidden: 128
  activation: 'relu'
  base_model: 'GCNConv'
  num_layers: 2
  drop_edge_rate_1: 0.2
  drop_edge_rate_2: 0.4
  drop_feature_rate_1: 0.3
  drop_feature_rate_2: 0.4
  tau: 0.4
  num_epochs: 10000
  weight_decay: 0.00001
CiteSeer:
  seed: 1234
  learning_rate: 0.001
  num_hidden: 256
  num_proj_hidden: 256
  activation: 'prelu'
  base_model: 'GCNConv'
  num_layers: 2
  drop_edge_rate_1: 0.2
  drop_edge_rate_2: 0.0
  drop_feature_rate_1: 0.3
  drop_feature_rate_2: 0.2
  tau: 0.9
  num_epochs: 10000
  weight_decay: 0.00001
CoraFull:
  seed: 1234
  learning_rate: 0.001
  num_hidden: 256
  num_proj_hidden: 256
  activation: 'relu'
  base_model: 'GCNConv'
  num_layers: 2
  drop_edge_rate_1: 0.4
  drop_edge_rate_2: 0.1
  drop_feature_rate_1: 0.0
  drop_feature_rate_2: 0.2
  tau: 0.7
  num_epochs: 10000
  weight_decay: 0.00001
ogbn-arxiv:
  seed: 83521
  learning_rate: 0.001
  num_hidden: 256
  num_proj_hidden: 256
  activation: 'relu'
  base_model: 'GCNConv'
  num_layers: 2
  drop_edge_rate_1: 0.1
  drop_edge_rate_2: 0.4
  drop_feature_rate_1: 0.1
  drop_feature_rate_2: 0.0
  tau: 0.7
  num_epochs: 10000
  weight_decay: 0.00001
Coauthor-CS:
  seed: 1234
  learning_rate: 0.001
  num_hidden: 256
  num_proj_hidden: 256
  activation: 'relu'
  base_model: 'GCNConv'
  num_layers: 2
  drop_edge_rate_1: 0.4
  drop_edge_rate_2: 0.1
  drop_feature_rate_1: 0.0
  drop_feature_rate_2: 0.2
  tau: 0.7
  num_epochs: 10000
  weight_decay: 0.00001
Amazon-Computer:
  seed: 1234
  learning_rate: 0.001
  num_hidden: 256
  num_proj_hidden: 256
  activation: 'relu'
  base_model: 'GCNConv'
  num_layers: 2
  drop_edge_rate_1: 0.4
  drop_edge_rate_2: 0.1
  drop_feature_rate_1: 0.0
  drop_feature_rate_2: 0.2
  tau: 0.7
  num_epochs: 10000
  weight_decay: 0.00001

